<?php
/**
 * Webinse
 *
 * PHP Version 5.6.23
 *
 * @category    Webinse
 * @package     Webinse_CalendarEvents
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * Template for Webinse_CalendarEvents
 *
 * @category    Webinse
 * @package     Webinse_CalendarEvents
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
?>
<?php $collection = $this->getAllEvents(); ?>
<script>
    $j(document).ready(function () {
        $j('#calendar').fullCalendar({
            events: <?php echo $this->getAllEvents() ?>,

            viewRender: function (view, element) {
                var now = new Date();
                var end = new Date();
                var month = now.getMonth();
                now.setMonth(month - <?php echo $this->getNumberOfPrevMonths() ?>);
                end.setMonth(month + <?php echo $this->getNumberOfNextMonths() ?>);


                if (end < view.end) {
                    $j("#calendar .fc-next-button").hide();
                    return false;
                }
                else {
                    $j("#calendar .fc-next-button").show();
                }

                if (view.start < now) {
                    $j("#calendar .fc-prev-button").hide();
                    return false;
                }
                else {
                    $j("#calendar .fc-prev-button").show();
                }
            }
        })
    });
</script>
<div id='calendar'></div>
